### ISSUE TITLE
Please add Dark mode to Joi Playground

### ISSUE THREAD

**Issue by Kausik07** [hapijs/joi.dev#31]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): yes
* *is this issue affecting a production system?* (yes/no): yes

#### Context

* *node version*: 
* *module version*: 
* *environment* (e.g. node, browser, native): 
* *used with* (e.g. hapi application, another framework, standalone, ...):
* *any other relevant information*: I can't do development at night as playground does not have a dark mode in it.

#### What problem are you trying to solve?

So that devs don't lost their eyes

#### Do you have a new or modified API suggestion to solve the problem?
No, I am not a frontend dev

**Comment by Marsup** [comment]
I've transferred the issue to the right repo.

You can certainly try, just know that this repo hasn't been updated in quite a while, and there's not a lot of guidance on how to run it. Depending on how comfortable you are with nuxt it may be a challenge. https://github.com/hapijs/hapi.dev is super similar and can help get you up to speed though.

**Comment by Nargonath** [comment]
Dark mode is already supported on the website. There isn't a toggle for it though. It's based on your system preference. If you setup your OS to be in dark mode then the website is going to be in dark mode.

**Comment by Marsup** [comment]
Added with recent changes.
